# Install via CocoaPods pointing at current local codebase
use_frameworks!
pod 'RestKit/Network', :path => '../../'
pod 'RestKit/ObjectMapping', :path => '../../'
pod 'RestKit/CoreData', :path => '../../'
