# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

# Remove the default rake task so we can cleanly add RCov enforcement
Rake.application.remove_task(:default)

# Run the Cucumber Features after full test run
task :default => ['spec:rcov:verify', 'features:rcov:verify']

