RESTKIT_OAUTH2_CLIENT_ID = "4fa42a4a7184796662000001";
RESTKIT_OAUTH2_CLIENT_SECRET = "restkit_secret"
RESTKIT_CLIENT_PARAMS = {
  :id => RESTKIT_OAUTH2_CLIENT_ID, :secret => RESTKIT_OAUTH2_CLIENT_SECRET, :display_name=>"RestKit", :scope=>%w{read write}
}
