#!/bin/bash -e

# Configure RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
rvm rvmrc load

# Git submodules
git submodule update --init

# Bundler & CocoaPods
bundle
bundle exec pod install

# Run the build
bundle exec rake server:stop || true
bundle exec rake server:start
bundle exec rake test
bundle exec rake server:stop
