source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'RKSearchExample' do

  pod 'RestKit', :path => '../../', :subspecs => ['Network', 'ObjectMapping', 'Search']
end
