source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'RKTwitterCoreData' do
  pod 'RestKit', :path => '../../', :subspecs => ['Network', 'ObjectMapping', 'CoreData']

  target 'Generate Seed Database' do
    inherit! :search_paths
  end
end
