platform :ios, '8.0'
use_frameworks!

link_with 'RKTwitterCoreData', 'Generate Seed Database'

# Install via CocoaPods pointing at current local codebase
pod 'RestKit/Network', :path => '../../'
pod 'RestKit/ObjectMapping', :path => '../../'
pod 'RestKit/CoreData', :path => '../../'
